### ISSUE TITLE
[Steem-Challenger] - Not showing correct usernames

### ISSUE THREAD

**Issue by jayserdny** [tyraelll/Steem-Challenger#1]
#### Expected behavior
***
When you introduce your username to calculate the total pending payouts, results should show your username to make sure it is you.

#### Actual behavior
***
When I introduce my username, jaysermendez, the user "netuoso" appears in the results.

#### How to reproduce
***
To reproduce this issue you can do the following steps:

- Go to http://omeratagun.tk
- In the field with placeholder "Your username", introduce your username
- Press enter or the button "Give it to me"
-  Check the username on the results table

#### Environment Information
***
* Browser: Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)
* Operating system: macOS High Sierra

#### Recording Of The Bug
***
Here is a simple GIF reproducing this issue:
![omeratagun bug.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517814124/eduhkquunuxkdalz1clj.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jaysermendez/steem-challenger-not-showing-correct-usernames">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by omeratagunn** [comment]
Hey, jayserdn. 

Thank you for to letting me know. Issue happens because of steemit API. If you type my name over there, result will be certain. 

Next days, i will be working on to improve design and backend codes.
