### ISSUE TITLE
Steem Challanger 2.0 Website showing wrong balance of user Steems in USD

### ISSUE THREAD

**Issue by iamank1t** [tyraelll/Steem-Challenger#10]
#### Note
This project is amazing and i always used this. I also want to contribute my knowledge on this project but let leave this for later. Today i see the new version of steem challenger and get excited. I used it and i love the design but i see some little bugs in the project.

#### Expected behavior
Website wallet section needs to show user account Steem balance after converting them in US Dollars.
The other bug is in website responsiveness, when i switch website on my mobile the pending posts table column "payout in USD" cropped and become invisible.  

#### Actual behavior
But website wallet section didn't converting my steem balance in us dollars. It show me my steem balance as it is with US $ sign.

![Screen Shot 2018-02-25 at 6.41.42 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519564685/aa3of1coaykqykktbi1j.png)

![Screen Shot 2018-02-25 at 6.54.29 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519565631/ufc5iqaxgpmgp6ggdofl.png)

#### How to reproduce
To reproduce the bug do the following steps :-
- Open [this](https://steem.show) and enter your steemit username. 
- Now check your wallet section here you see that your steem balance with wrong calculation. If you have 10 steem then it show US $ 10, but it needs first to multiply your balance first with 1 steem price in USD and then shows in wallet section.
- Now to see other bug, just decrease your screen window to mobile screen width and then head to the pending payout table and you see the column "pending payout in USD is cropped".
<pre> <code>* Operating system: Mac OS 11
* Browser: Google Chrome
</code></pre>

#### Solution for this :-
There were two solution for this which are following :-
1. If you want to shows the actuall balance of user steem the please remove "US $" thing.
2. Or, if you want to show the steem balance in US $ then first multiply total steem with the value of 1 steem.
3. For pending payout table responsiveness, just add vertical scrollbar to the table.
   

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@iamankit/website-showing-wrong-balance-of-user-steems-in-usd">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by hernandev** [comment]
@iamank1t Did the last update fix all of those issues for you?
