### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [tyraelll/Steem-Challenger#19]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by omeratagunn** [comment]
Hey @jbeguna04. You can work on it, but i can not guarantee you that it will be merged.

**Comment by jbeguna04** [comment]
Thanks sir. Ill do my best to satisfy you

**Comment by hernandev** [comment]
@jbeguna04 just be sure to notice, the current logo is the one at https://steem.show.
