### ISSUE TITLE
Steem Challenger - Bug Hunting + Bug Fixing

### ISSUE THREAD

**Issue by onurkahveci** [tyraelll/Steem-Challenger#5]
![steemchallenger.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519064825/fxeqrei1excl2mqlwvpk.png)

Steem challenger is a project created by omeratagun, one of our supervisor; for the people who posts via utopian, dmania, dlive and many other projects which includes beneficaries to calculate rewards.

#### Expected behavior
Possible rewards for posts created by users should be calculated.

![onursonuc2.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519065126/tkhtoo3gfhuiuq1rn0qq.png)

#### Actual behavior
Reward for resteemed posts are also calculated.

![onur1sonuc.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519065136/idxmuwmg8ro0wrtdszwu.png)

#### How to reproduce

- Go to http://omeratagun.tk
- In the field with placeholder "Your username", introduce your username
- Press enter or the button "Give it to me"
- Check the username on the results table
- Resteem one post with high reward (pending one)
- Go to http://omeratagun.tk
- In the field with placeholder "Your username", introduce your username
- Press enter or the button "Give it to me"
- Check the username on the results table

You will see that there is difference. (Rewards for resteemed posts are also calculated)
    
#### How to fix

![fixed part.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519065394/xwrn8h3pdmypafepma9y.png)

``` language
 and ($author==$meme)){
```
should be added to the source code. I also send a pull request to fix the problem. You can find the pull request [clicking here](https://github.com/tyraelll/Steem-Challenger/pull/4/).

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@onurkahveci/steem-challenger-bug-hunting-bug-fixing">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by omeratagunn** [comment]
Perfect
