### ISSUE TITLE
Incorrect username prevents search from taking place without URL edit

### ISSUE THREAD

**Issue by tobias-g1** [tyraelll/Steem-Challenger#9]
#### Expected behavior
As there is validation to allow you check the username I would expect that when a user hasn't entered a username which meets the validation requirements a user should not be able to submit the search.

#### Actual behavior
When you enter a username which doesn't exist and you submit the search the search field disappears and you get the search field back unless you edit the URL back to steem.show

#### How to reproduce
1. Go to http://steem.show
2. Within the search field enter a username that doesn't exist such as '#'
3. The search field will disappear and you won't be able to get it to return unless you remove the search parameters and return the URL to steem.show

#### Enviroment

* Browser: Version 64.0.3282.186 (Official Build) (64-bit)
* Operating system: MacOS HighSierra Version 10.13 (17A365)

#### Recording Of The Bug
A recording of the bug can be found here: https://d.tube/#!/v/tobias-g/hpwy8zap
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/incorrect-username-prevents-search-from-taking-place-without-url-edit">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by omeratagunn** [comment]
@hernandev He has a point. Please create condition for special characters or null returns

**Comment by hernandev** [comment]
Got it, I'll fix it as soon as possible

**Comment by hernandev** [comment]
@tobias-g1 please refresh the website and try a wrong username.

let me know
